$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string
  ref_transcriptome:
    type: string

required:
  - samples
  - ref_transcriptome
